behaviors:
  Balance_imp:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      #time_horizon: 32
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      # curiosity:
      #   strength: 0.02
      #   gamma: 0.99
      #   encoding_size: 256
      #   learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 90e6
    time_horizon: 1000
    summary_freq: 100000
    threaded: true
    checkpoint_interval: 500000  
environment_parameters:
  cases:
    curriculum:
      - name: Lesson0 # This is the start of the first lesson
        completion_criteria:
          measure: reward
          behavior: Balance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 10000
        value: 4.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Balance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 1.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Balance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 2.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Balance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 3.0
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Balance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 4.0
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: Balance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 5.0
      - name: end
        value: 5.0