default_settings: null
behaviors: !!python/object/apply:mlagents.trainers.settings.DefaultTrainerDict
  args:
  - !!python/name:mlagents.trainers.settings.TrainerSettings ''
  dictitems:
    Balance:
      trainer_type: ppo
      hyperparameters:
        batch_size: 64
        buffer_size: 12000
        learning_rate: 0.001
        beta: 0.003
        epsilon: 0.2
        lambd: 0.99
        num_epoch: 3
        learning_rate_schedule: linear
      network_settings:
        normalize: true
        hidden_units: 128
        num_layers: 2
        vis_encode_type: simple
        memory: null
      reward_signals:
        extrinsic:
          gamma: 0.99
          strength: 1.0
          network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
            vis_encode_type: simple
            memory: null
      init_path: null
      keep_checkpoints: 5
      checkpoint_interval: 500000
      max_steps: 50000000
      time_horizon: 1000
      summary_freq: 100000
      threaded: true
      self_play: null
      behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  cases:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1488
          value: 0.0
      name: Lesson0
      completion_criteria:
        behavior: Balance
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 10000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1489
          value: 1.0
      name: Lesson1
      completion_criteria:
        behavior: Balance
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 10000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1490
          value: 2.0
      name: Lesson2
      completion_criteria:
        behavior: Balance
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 10000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1491
          value: 3.0
      name: Lesson3
      completion_criteria:
        behavior: Balance
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 10000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1492
          value: 4.0
      name: Lesson4
      completion_criteria:
        behavior: Balance
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 10000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1493
          value: 5.0
      name: Lesson5
      completion_criteria:
        behavior: Balance
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 10000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1494
          value: 6.0
      name: end
      completion_criteria: null
checkpoint_settings:
  run_id: improved+increment1
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
